name: Deploy

on:
    pull_request:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: yarn

            - name: Build
              run: yarn build

            - name: Deploy to Skynet
              uses: SkynetLabs/deploy-to-skynet-action@v2
              with:
                  upload-dir: public
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  portal-url: https://fileportal.org
                  skynet-api-key: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && secrets.SKYNET_API_KEY || '' }}
                  registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && secrets.REGISTRY_SEED || '' }}
                  registry-datakey: web3extension.com
